<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-5JP91O4B" failures="1" tests="7" name="com.org.tests.APITest" time="8.143" errors="0" timestamp="2021-09-04T20:21:18 CEST" skipped="0">
  <testcase classname="com.org.tests.APITest" name="getAllRepo" time="1.223">
    <failure message="Total count changed as this is a dynamic value expected [643292] but found [643294]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Total count changed as this is a dynamic value expected [643292] but found [643294]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.org.tests.APITest.getAllRepo(APITest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- getAllRepo -->
  <system-out/>
  <testcase classname="com.org.tests.APITest" name="getRepoByLanguage" time="1.359"/>
  <system-out/>
  <testcase classname="com.org.tests.APITest" name="getRepoByDate" time="0.811"/>
  <system-out/>
  <testcase classname="com.org.tests.APITest" name="getRepoByTwoLanguages" time="1.499"/>
  <system-out/>
  <testcase classname="com.org.tests.APITest" name="getRepoByUser" time="1.502"/>
  <system-out/>
  <testcase classname="com.org.tests.APITest" name="getStarredRepo" time="1.362"/>
  <system-out/>
  <testcase classname="com.org.tests.APITest" name="dataNotFound" time="0.387"/>
  <system-out/>
</testsuite> <!-- com.org.tests.APITest -->
